-- Rootie Phase 1.0 — Seed data (plant_taxa)
-- Run after schema.sql and rls.sql. Safe to run multiple times (on conflict skip or replace as needed).

-- ~50 popular plant taxa for autocomplete: Monstera variants, common houseplants, synonyms included.
-- popularity_score: higher = suggested first (1–100 scale).

insert into public.plant_taxa (canonical_name, synonyms, popularity_score) values
  ('Monstera deliciosa', array['Monstera', 'Split-leaf philodendron', 'Swiss cheese plant'], 100),
  ('Monstera adansonii', array['Monstera monkey mask', 'Swiss cheese vine', 'Five holes plant'], 95),
  ('Monstera albo borsigiana', array['Monstera albo', 'Variegated Monstera', 'Monstera variegata'], 90),
  ('Monstera Thai Constellation', array['Thai Constellation', 'Monstera Thai'], 88),
  ('Monstera siltepecana', array['Silver Monstera', 'Monstera silver'], 70),
  ('Monstera obliqua', array['Monstera obliqua Peru'], 65),
  ('Monstera dubia', array['Shingle plant', 'Monstera shingle'], 60),
  ('Monstera pinnatipartita', array['Monstera pinnati'], 55),
  ('Philodendron hederaceum', array['Heartleaf philodendron', 'Philodendron scandens'], 92),
  ('Philodendron bipinnatifidum', array['Split-leaf philodendron', 'Philodendron selloum', 'Tree philodendron'], 85),
  ('Philodendron gloriosum', array['Velvet philodendron', 'Philodendron velvet'], 88),
  ('Philodendron melanochrysum', array['Black gold philodendron', 'Philodendron black gold'], 86),
  ('Philodendron pink princess', array['PPP', 'Pink princess philodendron'], 94),
  ('Philodendron micans', array['Velvet leaf philodendron', 'Philodendron velvet'], 82),
  ('Philodendron brasil', array['Philodendron Brazil', 'Philodendron hederaceum Brasil'], 80),
  ('Philodendron xanadu', array['Philodendron Xanadu', 'Winterbourn'], 75),
  ('Epipremnum aureum', array['Pothos', 'Devil''s ivy', 'Golden pothos', 'Scindapsus'], 98),
  ('Epipremnum pinnatum', array['Dragon tail', 'Cebu blue pothos', 'Epipremnum Cebu blue'], 84),
  ('Scindapsus pictus', array['Satin pothos', 'Silver pothos', 'Scindapsus silver'], 85),
  ('Alocasia amazonica', array['Alocasia Polly', 'African mask', 'Elephant ear'], 82),
  ('Alocasia zebrina', array['Zebra plant', 'Alocasia zebra'], 78),
  ('Alocasia black velvet', array['Alocasia Black Velvet', 'Black velvet'], 80),
  ('Alocasia reginula', array['Black velvet Alocasia', 'Little queen'], 72),
  ('Anthurium clarinervium', array['Velvet cardboard anthurium', 'Anthurium velvet'], 76),
  ('Anthurium crystallinum', array['Crystal anthurium', 'Anthurium crystal'], 74),
  ('Anthurium andraeanum', array['Flamingo flower', 'Anthurium red', 'Laceleaf'], 68),
  ('Calathea roseopicta', array['Calathea medallion', 'Rose painted calathea'], 80),
  ('Calathea orbifolia', array['Calathea round leaf', 'Orbifolia'], 75),
  ('Calathea lancifolia', array['Rattlesnake plant', 'Calathea rattlesnake'], 72),
  ('Maranta leuconeura', array['Prayer plant', 'Maranta prayer plant', 'Rabbit tracks'], 78),
  ('Ficus lyrata', array['Fiddle leaf fig', 'FLF', 'Ficus fiddle'], 90),
  ('Ficus elastica', array['Rubber plant', 'Rubber tree', 'Ficus rubber'], 85),
  ('Ficus benjamina', array['Weeping fig', 'Ficus tree'], 70),
  ('Sansevieria trifasciata', array['Snake plant', 'Mother-in-law''s tongue', 'Dracaena trifasciata'], 92),
  ('Sansevieria cylindrica', array['Cylindrical snake plant', 'Spear sansevieria'], 65),
  ('Dracaena marginata', array['Dragon tree', 'Madagascar dragon tree'], 75),
  ('Dracaena fragrans', array['Corn plant', 'Dracaena corn', 'Happy plant'], 70),
  ('Zamioculcas zamiifolia', array['ZZ plant', 'Zamioculcas', 'Zanzibar gem'], 88),
  ('Spathiphyllum', array['Peace lily', 'Spathiphyllum peace lily'], 82),
  ('Aglaonema', array['Chinese evergreen', 'Aglaonema red', 'Aglaonema silver'], 78),
  ('Syngonium podophyllum', array['Arrowhead plant', 'Syngonium', 'Goosefoot'], 80),
  ('Syngonium pink', array['Pink Syngonium', 'Syngonium neon'], 72),
  ('Pilea peperomioides', array['Chinese money plant', 'Pilea', 'Pancake plant', 'UFO plant'], 86),
  ('Pilea cadierei', array['Aluminum plant', 'Pilea aluminum'], 60),
  ('Hoya carnosa', array['Wax plant', 'Hoya wax', 'Porcelain flower'], 82),
  ('Hoya obovata', array['Hoya obovata splash', 'Hoya splash'], 76),
  ('Hoya kerrii', array['Sweetheart hoya', 'Valentine hoya', 'Hoya heart'], 80),
  ('Tradescantia zebrina', array['Wandering Jew', 'Inch plant', 'Tradescantia purple'], 78),
  ('Tradescantia nanouk', array['Tradescantia pink', 'Fantasy Venice'], 72),
  ('Peperomia obtusifolia', array['Baby rubber plant', 'Peperomia green'], 70),
  ('Peperomia caperata', array['Radiator plant', 'Peperomia ripple'], 68),
  ('Crassula ovata', array['Jade plant', 'Money tree', 'Jade tree'], 85),
  ('Echeveria', array['Echeveria succulent', 'Hen and chicks'], 75),
  ('Kalanchoe blossfeldiana', array['Flaming Katy', 'Kalanchoe'], 62),
  ('Haworthia', array['Haworthia succulent', 'Zebra cactus'], 68),
  ('Sedum morganianum', array['Burro''s tail', 'Donkey tail', 'Sedum burro'], 74),
  ('Senecio rowleyanus', array['String of pearls', 'Senecio pearls'], 84),
  ('Ceropegia woodii', array['String of hearts', 'Chain of hearts', 'Rosary vine'], 86),
  ('Begonia rex', array['Rex begonia', 'Painted leaf begonia'], 70),
  ('Oxalis triangularis', array['Purple shamrock', 'False shamrock', 'Oxalis purple'], 68)
on conflict ( (lower(canonical_name)) ) do update set
  synonyms = excluded.synonyms,
  popularity_score = excluded.popularity_score;
 